language: php

sudo: required

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '7.4'
  - '8.0'
  - '8.1'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant

before_script:
 - phpunit --version
 - travis_retry composer install

script:
  - ant gitlab

after_success:
 - travis_retry php vendor/bin/php-coveralls -v
